export enum CallSessionStatus {
    // Overall Call Session Status
    CALL_SESSION_SUCCESSFUL = "CALL_SESSION_SUCCESSFUL",
    CALL_SESSION_FAILED = "CALL_SESSION_FAILED",
    VAPI_AGENT_CALL_TRANSCRIPT_RECEIVED = "VAPI_AGENT_CALL_TRANSCRIPT_RECEIVED",
    PROCESSED_TRANSCRIPT= "PROCESSED_TRANSCRIPT",
    FAILED_TO_PROCESS_TRANSCRIPT = "FAILED_TO_PROCESS_TRANSCRIPT",
  }